#pragma once
#include <string>
using namespace std;

// Đại diện cho tài khoản người dùng (User hoặc Admin)
class UserAccount {
public:
    string username;
    string hashedPassword;
    string fullName;
    string email;
    string phone;
    bool isAdmin;                   // true = admin, false = user thường
    bool isLocked;                  // true = đã bị khoá, false = bình thường
    bool isPasswordAutoGenerated;   // true = mật khẩu tự sinh

    UserAccount();
    UserAccount(const std::string& username,
        const std::string& hashedPassword,
        const std::string& fullName,
        const std::string& email,
        const std::string& phone,
        bool isAdmin = false,
        bool isLocked = false,
        bool isPasswordAutoGenerated = false);

    void displayInfo() const;
    bool checkPassword(const std::string& inputPassword) const;
};